# Site settings
title: WikiLog
url: "https://shouts77.github.io"
baseurl: ""
description: >
    shouts 블로그

# My information
email: shouts98@gmail.com
author: shouts
profile: new to programming
twitter_username: shouts2713531
github_username: shouts77 
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: shouts
  shortname: shouts 
utterances:
  repo: shouts77/shouts77.github.io
  issue-term: url
  label: Comment
  branch: master

giscus:
  repo: shouts77/shouts77.github.io
  repo_id: R_kgDOIpvPCA
  category: Announcements
  category_id: DIC_kwDOIpvPCM4CTabv

google_analytics:
  ua:
# ua: UA-110224147-1

google_adsense:
  client:
# client: ca-pub-3675948545737694

blame: "https://github.com/shouts77/shouts77.github.io/blame/master/_wiki"
edit: "https://github.com/shouts77/shouts77.github.io/edit/master/_wiki"
issue: "https://github.com/shouts77/shouts77.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
